name: Python package

on:
  push:
    branches:
      - feature/timoris-core  # Trigger the build only on this branch
  pull_request:
    branches:
      - feature/timoris-core  # Trigger on PRs targeting this branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Use Python version 3.8 (adjust if needed)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from your requirements file
        pip install pytest  # Ensure pytest is installed

    - name: Run tests
      run: |
        pytest test/  # Run all tests using pytest
